name    'pivotal-pivotal_repo'
version '0.1.1'
source 'https://github.com/pivotal/app-manage/tree/master/puppet/pivotal-pivotal_repo'
author 'pivotal'
license 'Apache License, Version 2.0'
summary 'Manages Pivotal yum/apt repositories'
description 'Manages Pivotal YUM/APT Repositories'
project_page 'https://github.com/pivotal/app-manage/tree/master/puppet/pivotal-pivotal_repo'

## Add dependencies, if any:
dependency 'maestrodev/wget'
dependency 'puppetlabs/apt'

